# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thjc4PPIFVfDtSXCtB5cLXDrEs-cb3pd
"""
import streamlit as st
import joblib

model = joblib.load("model.joblib")
vectorizer = joblib.load("vectorizer.joblib")

st.title("🧠 Sentiment Analysis App")

text = st.text_area("Enter text")

if st.button("Predict"):
    vec = vectorizer.transform([text])
    pred = model.predict(vec)[0]

    if pred == 0:
        st.error("🔴 Negative")
    elif pred == 1:
        st.info("🟡 Neutral")
    else:
        st.success("🟢 Positive")
