# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thjc4PPIFVfDtSXCtB5cLXDrEs-cb3pd
"""

import streamlit as st
import joblib
import os

st.title("Sentiment Analysis App")

st.write("Files:", os.listdir())

model = joblib.load("model.joblib")
vectorizer = joblib.load("vectorizer.joblib")