# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thjc4PPIFVfDtSXCtB5cLXDrEs-cb3pd
"""

import streamlit as st
import pickle

# Load trained model and vectorizer
model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

st.set_page_config(page_title="Sentiment Analysis", page_icon="🧠")

st.title("🧠 Sentiment Analysis App")
st.write("Predict sentiment: Negative | Neutral | Positive")

text = st.text_area("Enter text here")

if st.button("Predict Sentiment"):
    if text.strip() == "":
        st.warning("Please enter some text")
    else:
        text_vector = vectorizer.transform([text])
        prediction = model.predict(text_vector)[0]

        if prediction == 0:
            st.error("🔴 Negative Sentiment")
        elif prediction == 1:
            st.info("🟡 Neutral Sentiment")
        elif prediction == 2:
            st.success("🟢 Positive Sentiment")